name: Main
on:
  push:
    branches:
      - "develop"
      - "feature/update**"
      - "feature/server_esm**"
    paths-ignore:
      - "docs/**"
      - "bin/**"
      - ".github/workflows/main-docker.yml"
    tags:
      - "v*"
  workflow_dispatch:    

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  make-electron:
    name: Make Electron
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: macos
            image: macos-latest
          - name: linux
            image: ubuntu-latest
          - name: windows
            image: windows-latest
    runs-on: ${{ matrix.os.image }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up node & dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Set up Python for appdmg to be installed
        if: ${{ matrix.os.name == 'macos' }}
        run: brew install python-setuptools
      - name: Install dependencies
        run: npm ci
      - name: Update build info
        run: npm run update-build-info
      - name: Run electron-forge
        run: npm run make-electron
      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os.name }}
          path: out/make/**