name: Release

on:
  push:

jobs:
  build-windows-installer:
    name: Build Windows Installer
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run installer build
        run: npm run make-electron
      
      - name: Publish installer artifact
        uses: actions/upload-artifact@v3
        with:
          name: Trilium Notes for Windows (.exe)
          path: out/make/squirrel.windows/x64/*.exe