name: Renovate
on:
  schedule:
    # Run every day at 1 AM UTC (before the nightly build at 2 AM UTC)
    - cron: '0 1 * * *'
  # Allow manual triggering
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  renovate:
    name: Run Renovate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v41.0.3
        with:
          configurationFile: renovate.json
          token: ${{ secrets.GITHUB_TOKEN }}